export { default as UserQueries } from './user.queries'
export { default as ChannelTemplateQueries } from './channels/template'
export { default as ChannelDashboardQueries } from './channels/dashboard'
export { default as ChannelInsightQueries } from './channels/insight'
export { default as CamapaignQueries } from './campaigns/campaigns'
export { default as CampaignDashboardQueries } from './campaigns/dashboard'
export { default as CampaignInsightQueries } from './campaigns/insight'
