const initialState = {
  editingCustomerId: '',
  list: [
    ...[...Array(5)].map((_, index) => [
      { id: index + 1 },
      {
        _id: '5fb8e47092add608def8fdc0',
        label: 'Full Name',
        name: 'Ariya MMS',
        is_enabled: true,
        datatype: 'str',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc1',
        label: 'First Name',
        name: 'Ariya',
        is_enabled: true,
        datatype: 'str',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc2',
        label: 'Last Name',
        name: 'MMS',
        is_enabled: true,
        datatype: 'str',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc3',
        label: 'Gender',
        name: 'Male',
        is_enabled: true,
        datatype: 'radio',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc4',
        label: 'Date of birth',
        name: '1998/11/13',
        is_enabled: true,
        datatype: 'date',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc5',
        label: 'Age',
        name: '25',
        is_enabled: true,
        datatype: 'str',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc6',
        label: 'Mobile Number',
        name: '097123456789',
        is_enabled: true,
        datatype: 'number',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },

      {
        _id: '5fb8e47092add608def8fdc7',
        label: 'Email',
        name: 'ariya.mms@gmail.com',
        is_enabled: true,
        datatype: 'email',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
    ]),
    ...[...Array(5)].map((_, index) => [
      { id: index + 6 },
      {
        _id: '5fb8e47092add608def8fdc0',
        label: 'Full Name',
        name: 'Sarah ramazani',
        is_enabled: true,
        datatype: 'str',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc11',
        label: 'First Name',
        name: 'Sarah',
        is_enabled: true,
        datatype: 'str',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc22',
        label: 'Last Name',
        name: 'Ramazani',
        is_enabled: true,
        datatype: 'str',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc33',
        label: 'Gender',
        name: 'Female',
        is_enabled: true,
        datatype: 'radio',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc44',
        label: 'Date of birth',
        name: '1990/09/23',
        is_enabled: true,
        datatype: 'date',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc55',
        label: 'Age',
        name: '30',
        is_enabled: true,
        datatype: 'str',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc66',
        label: 'Mobile Number',
        name: '097123456789',
        is_enabled: true,
        datatype: 'number',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },

      {
        _id: '5fb8e47092add608def8fdc77',
        label: 'Email',
        name: 'sara@gmail.com',
        is_enabled: true,
        datatype: 'email',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
    ]),
    ...[...Array(10)].map((_, index) => [
      { id: index + 5 },
      {
        _id: '5fb8e47092add608def8fdc000',
        label: 'Full Name',
        name: 'Ali Ghanbari',
        is_enabled: true,
        datatype: 'str',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc111',
        label: 'First Name',
        name: 'Ali',
        is_enabled: true,
        datatype: 'str',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc222',
        label: 'Last Name',
        name: 'Ghanbari',
        is_enabled: true,
        datatype: 'str',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc333',
        label: 'Gender',
        name: 'Male',
        is_enabled: true,
        datatype: 'radio',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc444',
        label: 'Date of birth',
        name: '1998/09/23',
        is_enabled: true,
        datatype: 'date',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc555',
        label: 'Age',
        name: '25',
        is_enabled: true,
        datatype: 'str',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc666',
        label: 'Mobile Number',
        name: '097123456789',
        is_enabled: true,
        datatype: 'number',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },

      {
        _id: '5fb8e47092add608def8fdc777',
        label: 'Email',
        name: 'sadeghahmad@gmail.com',
        is_enabled: true,
        datatype: 'email',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
    ]),
    ...[...Array(19)].map((_, index) => [
      { id: index + 41 },
      {
        _id: '5fb8e47092add608def8fdc888',
        label: 'Full Name',
        name: 'Farshad R',
        is_enabled: true,
        datatype: 'str',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc9999',
        label: 'First Name',
        name: 'Farshad',
        is_enabled: true,
        datatype: 'str',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc10111',
        label: 'Last Name',
        name: 'Roozbahani',
        is_enabled: true,
        datatype: 'str',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc1111111',
        label: 'Gender',
        name: 'Male',
        is_enabled: true,
        datatype: 'radio',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc12',
        label: 'Date of birth',
        name: '1993/11/23',
        is_enabled: true,
        datatype: 'date',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc13',
        label: 'Age',
        name: '28',
        is_enabled: true,
        datatype: 'str',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
      {
        _id: '5fb8e47092add608def8fdc14',
        label: 'Mobile Number',
        name: '09712323789',
        is_enabled: true,
        datatype: 'number',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },

      {
        _id: '5fb8e47092add608def8fdc15',
        label: 'Email',
        name: 'farshad@gmail.com',
        is_enabled: true,
        datatype: 'email',
        operations: ['eq', 'gt', 'gte', 'lt', 'lte'],
      },
    ]),
  ],
}

const reducers = {
  SET_CUSTOMERS_LIST: (state, list) => ({ ...state, list }),
  SET_EDITING_CUSTOMER_ID: (state, id) => ({ ...state, editingCustomerId: id }),
}

export default (state = initialState, { type, payload }) =>
  reducers[type] ? reducers[type](state, payload) : state
